[Settings]
  ID = "832aff74-f4c5-4477-8d50-a240cee9ccdb"
  Path = "site"

[Build]
  Publish = "site"
  Command = "make build"
  Functions = "functions"

[[redirects]]
from = "/test-redirect"
to = "https://netlify.com"

[[redirects]]
from = "/test-redirect-with-query"
to = "https://netlify.com?utm_source=test"

[[redirects]]
from = "/api/*"
to = "/.netlify/functions/:splat"
status = 200

[[redirects]]
from = "/admin/*"
status = 200
force = true
conditions = { Role = "admin" }
