[Settings]
  ID = "832aff74-f4c5-4477-8d50-a240cee9ccdb"
  Path = "site"

[Build]
  Publish = "site"
  Command = "make build"
  Functions = "functions"

[[redirects]]
from = "/test?utm_source=david-test"
to = "https://netlify.com"
